@Library('jenkins-shared-lib') _
import org.example.Utils

library(
  identifier: 'jenkins-shared-lib@main',
  retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/meherjahnavi1/jenkins-shared-lib.git'
  ])
)

pipeline {
  agent any
  options { timestamps() }

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Hello') {
      steps { hello('Meher') }
    }

    stage('Python Setup') {
      steps {
        pythonSetup('requirements.txt')   // creates .venv; installs reqs if file exists
      }
    }

    stage('Tests') {
      when {
        anyOf {
          expression { fileExists('tests') }
          expression { fileExists('pytest.ini') || fileExists('pyproject.toml') }
        }
      }
      steps {
        script {
          def u = new Utils(this)
          u.banner('Running pytest')
        }
        sh '''
          . .venv/bin/activate || true
          pytest -q || true
        '''
      }
    }
  }

  post {
    success { echo "✅ ${env.JOB_NAME} #${env.BUILD_NUMBER} OK" }
    failure { echo "❌ ${env.JOB_NAME} #${env.BUILD_NUMBER} FAILED" }
  }
}